cog example
EnokiUN/voltage pull request #40
Opened 2022-04-07 19:45 UTC by yonipy

## Summary

## Checklist

- [ ] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

2022-04-07 20:21 UTC, RGBCube commented on examples/cogs.py
> +import Cog
Wrong

2022-04-08 07:44 UTC, ysIgnacio requested changes

2022-04-08 07:44 UTC, ysIgnacio commented on examples/cogs.py
> +import Cog
use `from voltage.ext.commands import Cog`

2022-04-08 07:47 UTC, ysIgnacio commented on examples/cogs.py
> +def setup(client) -> Cog:
client is not defined(?)

2022-04-08 20:11 UTC, closed without merging

2022-04-08 20:14 UTC, ysIgnacio commented
why close